# Generated by Django 5.2.4 on 2025-09-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('pubDate', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('imagePath', models.ImageField(default='i.jpg', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packageID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('packageTitle', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image_path', models.ImageField(default='i.jpg', upload_to='uploads/')),
                ('duration', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='powerPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('imagePath', models.ImageField(default='i.jpg', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('packageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.package')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.user')),
            ],
        ),
    ]
